const assert = require('node:assert/strict');
const fs = require('node:fs');
const admin = require('../assets/js/admin.js');
const auth = require('../assets/js/admin-auth.js');
const adminSource = fs.readFileSync(require.resolve('../assets/js/admin.js'), 'utf8');
const configSource = fs.readFileSync(require.resolve('../assets/js/admin-config.test.js'), 'utf8');
const adminHtml = fs.readFileSync(require.resolve('../admin/index.html'), 'utf8');
const visibleAdminHtml = adminHtml.replace(/<script\b[^>]*>[\s\S]*?<\/script>/giu, ' ').replace(/<[^>]+>/gu, ' ').replace(/\s+/gu, ' ').trim();

const storage = () => { const values = new Map(); return {getItem: (key) => values.get(key) || null, setItem: (key, value) => values.set(key, value), removeItem: (key) => values.delete(key), values}; };
const config = {environment: 'TEST', issuer: auth.TEST_ISSUER, openid_configuration_url: auth.TEST_DISCOVERY_URL, client_id: auth.TEST_CLIENT_ID, redirect_uri: 'https://admin.test/admin/', scopes: ['openid', 'email', 'profile']};
const runtime = {environment: 'TEST', api_url: admin.TEST_ADMIN_API_URL, auth: config};
const cryptoImpl = {getRandomValues: (bytes) => { bytes.fill(7); return bytes; }, subtle: crypto.subtle};

assert.equal(admin.STATUSES.length, 9);
assert.deepEqual(auth.OIDC_SCOPES, ['openid', 'email', 'profile']);
assert.deepEqual(admin.OPERATIONAL, ['lifecycle_status', 'owner', 'priority', 'next_action', 'next_contact_at', 'decision', 'internal_comment']);
assert.deepEqual(admin.DISPLAY_VALUES, {application_pending:'Новая заявка', pending:'На рассмотрении', approved:'Одобрена', rejected:'Отказано'});
assert.ok(admin.FIELDS.includes('occupation'));
assert.ok(admin.FIELDS.includes('acquaintance_methods'));
assert.equal(admin.FIELDS.includes('unacceptable_behavior'), false);
assert.match(adminSource, /Загрузка заявок/);
assert.match(adminSource, /Заявок по выбранным условиям нет/);
assert.match(adminSource, /Сервис временно недоступен\. Попробуйте позже/);
assert.match(adminSource, /Чем наполнена ваша жизнь кроме работы\?/);
assert.match(adminSource, /Почему вам интересно попробовать «Гравитацию»\?/);
assert.match(adminSource, /Что вы обычно привносите в компанию людей\?/);
assert.match(adminSource, /За что вас ценят друзья и знакомые\?/);
assert.match(adminSource, /Какие знакомства вам сейчас интересны\?/);
assert.match(adminSource, /Откуда узнали о нас\?/);
assert.doesNotMatch(adminSource, /Статус заявки \(legacy\)/);
assert.match(adminSource, /telegram:'Профиль или мессенджер'/);
assert.match(adminHtml, /Профиль или мессенджер/);
assert.doesNotMatch(adminHtml, />Telegram</);
assert.match(visibleAdminHtml, /ГРАВИТАЦИЯ ЗАЯВКИ/);
assert.doesNotMatch(visibleAdminHtml, /\b(?:JWT|OIDC|API|token|scope|authorizer|endpoint|backend|YDB|TEST|PROD|ADMIN)\b|токен|Object Storage|HTTP 40[13]|internal error|application_id|participant_id|photo_object_id/iu);
['OIDC-модуль', 'OIDC вход', 'Admin API', 'Access token', 'ID token', '<h3>Operational', 'item.application_id', 'class="env-badge">TEST'].forEach((technicalText) => assert.ok(!adminSource.includes(technicalText), technicalText));
assert.match(adminSource, /У вас нет прав для просмотра заявок/);
assert.match(adminSource, /У вас нет прав для этого действия/);
assert.match(adminSource, /Сервис временно недоступен\. Попробуйте позже/);
assert.match(adminSource, /=> auth\.getGatewayToken\(\)/);
assert.doesNotMatch(adminSource, /=> auth\.getAccessToken\(\)/);
assert.ok(!fs.readFileSync(require.resolve('../assets/js/admin-auth.js'), 'utf8').includes('localStorage'));
assert.match(configSource, /window\.__V5_ADMIN_CONFIG__ = Object\.freeze/);
assert.match(configSource, /api_url: 'https:\/\/d5ds805l71s68liu6ge4\.fovt0b64\.apigw\.yandexcloud\.net'/);
assert.doesNotMatch(configSource, /\b(?:client_secret|access_token|id_token|refresh_token)\b\s*:/iu);
assert.match(configSource, /aje25t7tefbfr547phru/);
assert.match(configSource, /https:\/\/auth\.yandex\.cloud\/\.well-known\/openid-configuration/);
assert.match(configSource, /http:\/\/127\.0\.0\.1:8000\/admin\//);
assert.match(configSource, /scopes: Object\.freeze\(\['openid', 'email', 'profile'\]\)/);
assert.doesNotMatch(configSource, /admin:read|admin:write/);
assert.match(adminHtml, /admin-config\.test\.js[\s\S]*admin-auth\.js/);

(async () => {
  assert.deepEqual(auth.normalizeConfig(config).scopes, ['openid', 'email', 'profile']);
  assert.throws(() => auth.normalizeConfig({...config, scopes: ['openid', 'email']}), /oidc_configuration_required/);
  assert.throws(() => auth.normalizeConfig({...config, scopes: [...config.scopes, 'admin:read']}), /oidc_configuration_required/);
  assert.throws(() => auth.normalizeConfig({...config, environment: 'PROD'}), /oidc_configuration_required/);
  assert.throws(() => auth.normalizeConfig({...config, client_id: 'prod-client'}), /oidc_configuration_required/);
  assert.throws(() => auth.normalizeConfig({...config, redirect_uri: 'http://admin.test/admin/'}), /oidc_configuration_required/);
  assert.throws(() => auth.createAuthClient({config, cryptoImpl, storage: storage(), location: {href: 'https://other.test/admin/'}, fetchImpl: async () => ({ok: false})}), /oidc_configuration_required/);
  assert.equal(await auth.pkceChallenge('dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk', crypto), 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM');
  const transient = storage(); let assigned = '';
  const payload = Buffer.from(JSON.stringify({iss:'https://issuer.test', aud:'v5-test-spa', sub:'private-subject', exp:12345, scope:'openid email profile', email:'private@example.test'})).toString('base64url');
  const idToken = `header.${payload}.signature`;
  const accessToken = `access.${payload}.signature`;
  const oidc = auth.createAuthClient({config, cryptoImpl, storage: transient, location: {href: 'https://admin.test/admin/', assign: (url) => { assigned = url; }}, fetchImpl: async (url) => ({ok: true, json: async () => url.includes('openid') ? {authorization_endpoint: 'https://auth.yandex.cloud/authorize', token_endpoint: 'https://auth.yandex.cloud/token'} : {access_token: accessToken, id_token: idToken}})});
  await oidc.signIn();
  assert.match(assigned, /code_challenge_method=S256/);
  assert.ok(transient.values.has(auth.TRANSIENT_KEY));
  await assert.rejects(() => oidc.consumeCallback('https://admin.test/admin/?code=abc&state=wrong'), /oidc_state_mismatch/);
  const callbackState = JSON.parse(transient.getItem(auth.TRANSIENT_KEY)).state;
  const session = await oidc.consumeCallback(`https://admin.test/admin/?code=abc&state=${callbackState}`);
  assert.equal(session.gatewayToken, idToken);
  assert.equal(session.idToken, idToken);
  assert.equal(session.accessToken, undefined);
  const cyrillicPayload = Buffer.from(JSON.stringify({name:'Владимир Гравитация', email:'display@example.test'})).toString('base64url');
  assert.equal(auth.decodeJwt(`header.${cyrillicPayload}.signature`).name, 'Владимир Гравитация');
assert.equal(auth.displayNameFromClaims({name:'Ð’Ð»Ð°Ð´Ð¸Ð¼Ð¸Ñ€', given_name:'Владимир', family_name:'Гравитация'}), 'Владимир Гравитация');
assert.equal(auth.displayNameFromClaims({name:'Владимир Гравитация'}), 'Владимир Гравитация');
assert.equal(auth.normalizeOidcDisplayNameClaim('Владимир'), 'Владимир');
assert.equal(auth.normalizeOidcDisplayNameClaim('Ð’Ð»Ð°Ð´Ð¸Ð¼Ð¸Ñ€'), 'Владимир');
assert.equal(auth.normalizeOidcDisplayNameClaim('Admin'), 'Admin');
assert.equal(auth.displayNameFromClaims({name:'Ð’Ð»Ð°Ð´Ð¸Ð¼Ð¸Ñ€', preferred_username:'admin@example.test'}), 'Владимир');
assert.equal(auth.displayNameFromClaims({email:'user@example.test'}), '');
  assert.equal(oidc.getGatewayToken(), idToken);
  assert.equal(oidc.getIdToken(), idToken);
  assert.equal(transient.getItem(auth.TRANSIENT_KEY), null);
  assert.ok([...transient.values.values()].every((value) => !String(value).includes(accessToken) && !String(value).includes(idToken)));

  const missingIdStorage = storage();
  const missingIdClient = auth.createAuthClient({config, cryptoImpl, storage: missingIdStorage, location: {href: 'https://admin.test/admin/', assign: () => {}}, fetchImpl: async (url) => ({ok: true, json: async () => url.includes('openid') ? {authorization_endpoint: 'https://auth.yandex.cloud/authorize', token_endpoint: 'https://auth.yandex.cloud/token'} : {access_token: accessToken}})});
  await missingIdClient.signIn();
  const missingIdState = JSON.parse(missingIdStorage.getItem(auth.TRANSIENT_KEY)).state;
  await assert.rejects(() => missingIdClient.consumeCallback(`https://admin.test/admin/?code=abc&state=${missingIdState}`), /oidc_id_token_missing/);
  const accessDiagnostic = auth.tokenDiagnostics(accessToken, true);
  assert.deepEqual(accessDiagnostic, {is_jwt:true, segment_count:3, iss:'https://issuer.test', aud:'v5-test-spa', sub_present:true, exp:12345, claim_names:['aud','email','exp','iss','scope','sub'], scope:'openid email profile'});
  assert.deepEqual(auth.tokenDiagnostics('opaque-access-token', true), {is_jwt:false, segment_count:1, iss:null, aud:null, sub_present:false, exp:null, claim_names:[], scope:null});
  const calls = []; let authFailure = '';
  const client = admin.createClient({__V5_ADMIN_CONFIG__: runtime}, async (url, options = {}) => { calls.push({url, options}); return {status: 200, ok: true, json: async () => ({environment: 'TEST', applications: []})}; }, () => idToken, (reason) => { authFailure = reason; });
  await client.list({q: 'тест', sort: 'submitted_at', order: 'desc'});
  await client.save('PT-1', {owner: 'Влад'});
  assert.match(calls[0].url, /\/admin\/applications\?/);
  assert.equal(calls[0].options.headers.Authorization, `Bearer ${idToken}`);
  assert.notEqual(calls[0].options.headers.Authorization, `Bearer ${accessToken}`);
  assert.equal(calls[0].options.credentials, undefined);
  assert.equal(calls[1].options.headers['Content-Type'], 'application/json');
  await assert.rejects(() => admin.createClient({__V5_ADMIN_CONFIG__: runtime}, async () => ({ok: true}), () => null).list({}), /authentication_required/);
  const expired = admin.createClient({__V5_ADMIN_CONFIG__: runtime}, async () => ({status: 401, ok: false}), () => idToken, (reason) => { authFailure = reason; });
  await assert.rejects(() => expired.save('PT-1', {}), /session_expired/);
  assert.equal(authFailure, 'expired');
  const denied = admin.createClient({__V5_ADMIN_CONFIG__: runtime}, async () => ({status: 403, ok: false}), () => 'jwt');
  await assert.rejects(() => denied.list({}), /access_denied/);
  let requestsWithoutApi = 0;
  await assert.rejects(() => admin.createClient({}, async () => { requestsWithoutApi += 1; }, () => 'jwt').list({}), /admin_not_configured/);
  assert.equal(requestsWithoutApi, 0);
  for (const invalidConfig of [
    {environment: 'PROD', api_url: admin.TEST_ADMIN_API_URL, auth: config},
    {environment: 'TEST', api_url: 'https://prod.example.test', auth: config},
    {environment: 'TEST', api_url: `${admin.TEST_ADMIN_API_URL}/`, auth: config},
  ]) {
    let invalidCalls = 0;
    const invalid = admin.createClient({__V5_ADMIN_CONFIG__: invalidConfig}, async () => { invalidCalls += 1; }, () => 'jwt');
    await assert.rejects(() => invalid.list({}), /admin_not_configured/);
    assert.equal(invalidCalls, 0);
  }
  console.log('admin auth/ui contract: ok');
})();
