'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const apply=fs.readFileSync('apply/index.html','utf8'),api=fs.readFileSync('api/application.js','utf8'),js=fs.readFileSync('assets/js/apply.js','utf8'),all=apply+'\n'+api+'\n'+js;
const publicLegal=fs.readFileSync('privacy/index.html','utf8')+'\n'+fs.readFileSync('consent-pd/index.html','utf8');
const technicalTruth=api+'\n'+js+'\n'+fs.readFileSync('V5-CONTRACT.md','utf8')+'\n'+fs.readFileSync('LEGAL-TEXT-DEPENDENCY.md','utf8');
const screens=['Согласие','Контакты','О вас','Знакомства','Проверка'];
const fields=['full_name','age','gender','city','visit_krasnodar','phone','email','preferred_contact','profile_or_messenger_url','public_profile_url','occupation','life_outside_work','what_interested','what_participant_brings','what_friends_value','desired_connections','desired_connections_other','values_in_people','barriers_to_meeting','acquaintance_methods','acquaintance_methods_other','return_reason','source','photo_object_id'];
const removed=['interests','social_comfort','initiative','acquaintance_scenario','successful_evening','unacceptable_behavior','convenient_days','comfortable_price','telegram'];
assert.equal((apply.match(/data-step="/g)||[]).length,5);
screens.forEach(x=>assert.ok(apply.includes('>'+x+'<'),x));
fields.forEach(x=>{assert.ok(apply.includes('name="'+x+'"'),x);assert.ok(api.includes("'"+x+"'"),'API '+x)});
removed.forEach(x=>assert.equal(apply.includes('name="'+x+'"'),false,x));
assert.match(apply,/Я ознакомлен\(а\) с <a href="\/privacy\/"/);
assert.match(apply,/Даю согласие на обработку моих персональных данных на условиях <a href="\/consent-pd\/"/);
assert.match(apply,/от 14\.09\.2026<\/a>\./);
const visibleApply=apply.replace(/<[^>]+>/gu,' ').replace(/\s+/gu,' ').replace(/\s+([.])/gu,'$1').trim();
assert.ok(visibleApply.includes('Я ознакомлен(а) с Политикой обработки персональных данных.'));
assert.ok(visibleApply.includes('Даю согласие на обработку моих персональных данных на условиях Согласия на обработку персональных данных от 14.09.2026.'));
assert.equal((apply.match(/type="checkbox" name="(?:policy_acknowledged|personal_data_consent)"/g)||[]).length,2);
assert.match(apply,/><span>Фотография \*<\/span><input name="photo_upload" type="file"/);
assert.match(apply,/Фотография обязательна для отправки заявки\./);
assert.equal((apply.match(/class="consent"/g)||[]).length,2);
assert.equal(/checked/u.test(apply),false);
assert.equal(/PPD-2\.|CONSENT-PD-2\.|FORM-2\./u.test(apply),false);
assert.equal(/PPD-2\.|CONSENT-PD-2\.|FORM-2\./u.test(publicLegal),false);
assert.equal(/PPD-2\.1|CONSENT-PD-2\.1|LEGAL_PRODUCT_BLOCKED_REQUIRED_PHOTO/u.test(technicalTruth),false);
assert.match(technicalTruth,/PPD-2\.2/u);
assert.match(technicalTruth,/CONSENT-PD-2\.2/u);
assert.match(technicalTruth,/FORM-2\.2/u);
assert.ok(publicLegal.includes("['PPD','2.2'].join('-')"));
assert.ok(publicLegal.includes("['CONSENT','PD','2.2'].join('-')"));
assert.match(fs.readFileSync('legal/frozen/PPD-2.2.txt','utf8'),/Версия: 2\.2/u);
assert.match(fs.readFileSync('legal/frozen/CONSENT-PD-2.2.txt','utf8'),/Дата утверждения: 14\.09\.2026/u);
assert.match(apply,/Ссылка на профиль или мессенджер \(необязательно\)/);
assert.match(apply,/Ссылка на вашу страницу или сайт \(необязательно\)/);
assert.ok((apply.match(/Не указывайте сведения специальных категорий персональных данных\./g)||[]).length>=2);
assert.equal(apply.includes('Предпочитаю обсудить лично'),false);
assert.equal(apply.includes('<option>Telegram</option>'),false);
assert.equal(apply.includes('<option>WhatsApp</option>'),false);
assert.equal(apply.includes('>Формат<'),false);
assert.match(js,/current !== steps\.length - 1/);
assert.match(js,/event\.key === 'Enter'/);
assert.match(js,/term\.textContent = labels\[field\]/);
assert.match(js,/edit\.textContent = 'Изменить'/);
for(const section of ["['Контакты', 1", "['О вас', 2", "['Знакомства', 3"])assert.ok(js.includes(section),section);
for(const x of ['relationship_context','rules_consent','script.google.com','no-cors','photo_data','base64'])assert.equal(all.toLowerCase().includes(x),false,x);
assert.ok(api.includes('production_submission_disabled'));
console.log('V5 static contract tests passed');
