/**
 * ГРАВИТАЦИЯ — приём заявок сайта в Google Sheets.
 *
 * 1) Откройте таблицу "1. База участников — Google Sheets"
 * 2) Расширения → Apps Script
 * 3) Замените содержимое Code.gs этим файлом
 * 4) Развернуть → Новое развёртывание → Веб-приложение
 * 5) Выполнять от имени: Я
 * 6) У кого есть доступ: Все
 * 7) Скопируйте URL /exec в CONFIG.endpoint файла app.js
 */
const SPREADSHEET_ID='18fpmuIVxHG9IpZyET16zba1UypJN8Ta_pWR9GwWwdOk';
const PARTICIPANTS_SHEET='Участники';
const WEB_RAW_SHEET='Сайт — RAW';
const PARTICIPANT_HEADERS=['ID','Статус','Приоритет','Ответственный','Следующий шаг','Дата следующего контакта','Дата интервью','Решение','Комментарий','Ближайшее мероприятие','Количество посещений','Последнее участие','Дата заявки','Имя и фамилия','Возраст','Пол','Город','Посещение Краснодара','Телефон','Telegram','ВКонтакте','Instagram','Email','Как удобнее связаться?','Фото','Чем занимается','Жизнь кроме работы','Интересы','Контекст отношений','Какие знакомства интересны','Что ценит в людях','Что мешает знакомиться','Источник','Что заинтересовало','Ожидания от мероприятия','Удачный вечер','Что заставит вернуться','Комфорт в новой компании','Инициативность','Сценарий знакомства','Неприемлемое поведение','Удобные дни','Комфортная цена','Согласие на связь','Согласие ПДн','Правила участия','Канал заявки','UTM Source','UTM Medium','UTM Campaign','UTM Content','UTM Term','Referrer'];
const RAW_HEADERS=['Дата сервера','ID','Имя и фамилия','Возраст','Пол','Город','Телефон','Telegram','Email','Как удобнее связаться','Чем занимается','Интересы','Контекст отношений','Какие знакомства интересны','Что заинтересовало','Ожидания','Источник','Согласие ПДн','Правила участия','Страница','UTM Source','UTM Medium','UTM Campaign','UTM Content','UTM Term','Referrer','User Agent','Дата клиента'];
function doGet(){return json_({ok:true,service:'club-gravitation-applications'});}
function doPost(e){try{const p=(e&&e.parameter)||{};if(p.website)return json_({ok:true});require_(p.name,'name');require_(p.age,'age');require_(p.city,'city');require_(p.phone,'phone');require_(p.personal_data_consent,'personal_data_consent');require_(p.rules_consent,'rules_consent');const ss=SpreadsheetApp.openById(SPREADSHEET_ID),participants=ensureParticipants_(ss),raw=ensureRaw_(ss),id=makeId_(),now=new Date();raw.appendRow([now,id,p.name||'',p.age||'',p.gender||'',p.city||'',p.phone||'',p.telegram||'',p.email||'',p.preferred_contact||'',p.occupation||'',p.interests||'',p.relationship_context||'',p.connection_goal||'',p.interest_reason||'',p.expectations||'',p.source||'Сайт / лендинг',p.personal_data_consent||'',p.rules_consent||'',p.page_url||'',p.utm_source||'',p.utm_medium||'',p.utm_campaign||'',p.utm_content||'',p.utm_term||'',p.referrer||'',p.user_agent||'',p.submitted_at_client||'']);const row=Object.fromEntries(PARTICIPANT_HEADERS.map(h=>[h,'']));Object.assign(row,{'ID':id,'Статус':'Новая заявка','Дата заявки':now,'Имя и фамилия':p.name||'','Возраст':p.age||'','Пол':p.gender||'','Город':p.city||'','Телефон':p.phone||'','Telegram':p.telegram||'','Email':p.email||'','Как удобнее связаться?':p.preferred_contact||'','Чем занимается':p.occupation||'','Интересы':p.interests||'','Контекст отношений':p.relationship_context||'','Какие знакомства интересны':p.connection_goal||'','Источник':p.source||'Сайт / лендинг','Что заинтересовало':p.interest_reason||'','Ожидания от мероприятия':p.expectations||'','Согласие на связь':'Да','Согласие ПДн':p.personal_data_consent||'','Правила участия':p.rules_consent||'','Канал заявки':'Сайт','UTM Source':p.utm_source||'','UTM Medium':p.utm_medium||'','UTM Campaign':p.utm_campaign||'','UTM Content':p.utm_content||'','UTM Term':p.utm_term||'','Referrer':p.referrer||''});participants.appendRow(PARTICIPANT_HEADERS.map(h=>row[h]??''));return json_({ok:true,id});}catch(err){console.error(err);return json_({ok:false,error:String(err.message||err)});}}
function ensureParticipants_(ss){let sheet=ss.getSheetByName(PARTICIPANTS_SHEET);if(!sheet)sheet=ss.insertSheet(PARTICIPANTS_SHEET);const currentLastColumn=Math.max(sheet.getLastColumn(),1),currentHeaders=sheet.getRange(1,1,1,currentLastColumn).getValues()[0];PARTICIPANT_HEADERS.forEach((header,idx)=>{if(currentHeaders[idx]!==header)sheet.getRange(1,idx+1).setValue(header);});sheet.setFrozenRows(1);return sheet;}
function ensureRaw_(ss){let sheet=ss.getSheetByName(WEB_RAW_SHEET);if(!sheet)sheet=ss.insertSheet(WEB_RAW_SHEET);const current=sheet.getRange(1,1,1,RAW_HEADERS.length).getValues()[0];if(current.join('|')!==RAW_HEADERS.join('|')){sheet.getRange(1,1,1,RAW_HEADERS.length).setValues([RAW_HEADERS]);sheet.setFrozenRows(1);}return sheet;}
function makeId_(){return 'GR-WEB-'+Utilities.formatDate(new Date(),'Europe/Moscow','yyyyMMdd-HHmmss');}
function require_(value,name){if(!String(value||'').trim())throw new Error('Required field: '+name);}
function json_(obj){return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);}
