'use strict';
const LEGAL_VERSIONS={privacy:'PPD-2.0',consent:'CONSENT-PD-2.0'};
const FORM_VERSION='FORM-2.1';
const FORM_FIELDS=['full_name','age','gender','city','visit_krasnodar','phone','telegram','email','preferred_contact','public_profile_url','occupation','life_outside_work','interests','what_interested','event_expectations','desired_connections','values_in_people','barriers_to_meeting','social_comfort','initiative','acquaintance_scenario','successful_evening','return_reason','unacceptable_behavior','convenient_days','source'];
function reply(statusCode,body){return {statusCode,headers:{'content-type':'application/json; charset=utf-8'},body:JSON.stringify(body)};}
function parse(event){if(event?.httpMethod!=='POST')throw Error('method_not_allowed');if(!String(event.headers?.['content-type']||event.headers?.['Content-Type']||'').toLowerCase().startsWith('application/json'))throw Error('unsupported_media_type');return typeof event.body==='string'?JSON.parse(event.body):event.body;}
function validate(d){if(!d||typeof d!=='object'||Array.isArray(d))return'invalid_json';if(d.form_version!==FORM_VERSION)return'invalid_form_version';if(d.personal_data_consent!==true)return'consent_required';if(d.consent_version!==LEGAL_VERSIONS.consent||d.policy_version!==LEGAL_VERSIONS.privacy)return'invalid_legal_versions';if(d.website)return'bot_detected';for(const k of ['full_name','age','gender','city','phone'])if(!String(d[k]||'').trim())return`missing_${k}`;if(+d.age<25||+d.age>52)return'invalid_age';if(d.city!=='Краснодар'&&!String(d.visit_krasnodar||'').trim())return'missing_visit_krasnodar';for(const k of ['desired_connections','convenient_days'])if(d[k]!==undefined&&!Array.isArray(d[k]))return`invalid_${k}`;if(d.public_profile_url){try{const u=new URL(d.public_profile_url);if(!/^https?:$/u.test(u.protocol))return'invalid_public_profile_url';}catch{return'invalid_public_profile_url';}}return null;}
async function handler(event,{store,mode=process.env.APPLICATION_MODE}={}){if(mode!=='TEST')return reply(503,{error:'production_submission_disabled'});let data;try{data=parse(event);}catch(e){return reply(e.message==='method_not_allowed'?405:415,{error:e.message});}const error=validate(data);if(error)return reply(422,{error});const key=event.headers?.['idempotency-key']||event.headers?.['Idempotency-Key'];if(!key)return reply(400,{error:'idempotency_key_required'});if(!store?.get||!store?.put)return reply(503,{error:'test_store_unavailable'});const old=await store.get(key);if(old)return reply(200,{application_id:old.application_id,idempotent:true});const record={application_id:`TEST-${crypto.randomUUID()}`,idempotency_key:key,data,received_at:new Date().toISOString()};await store.put(key,record);return reply(201,{application_id:record.application_id,idempotent:false});}
module.exports={handler,validate,LEGAL_VERSIONS,FORM_VERSION,FORM_FIELDS};

